version: 2.1
orbs:
  node: circleci/node@4.0.0
jobs:
  test:
    docker:
      - image: "cimg/base:stable"
    steps:
      - checkout
      - node/install-packages
      - run:
          command: npm run test
workflows:
  test_my_app:
    jobs: [test]
