version: 2.1
orbs:
  node: circleci/node@4.0.0
jobs:
  test:
    docker:
      - image: circleci/node:10.0-browsers
        environment:
          CHROME_BIN: "/usr/bin/google-chrome"
    steps:
      - checkout
      - node/install-packages
      - run:
          command: npm test
workflows:
  test_my_app:
    jobs: [test]
